apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: svc-nginx
  name: svc-nginx
spec:
  ports:
  - name: 8080-80
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: svc-nginx
  type: ClusterIP
status:
  loadBalancer: {}
